#!/bin/sh

#chkconfig:2345 85 70
#description:unicorn shell

NAME="Unicorn"
ENV=production

ROOT_DIR="/vagrant_apps/my_todo"
GEMFILE="${ROOT_DIR}/Gemfile"

start()
{
  echo "start $NAME"
  su - vagrant -c $cd ${ROOT_DIR} && BUNDLE_GEMFILE=${GEMFILE} bundle exec rake unicorn:start"
}

stop()
{
  echo "stop $NAME"
  su - vagrant -c "cd ${ROOT_DIR} && BUNDLE_GEMFILE=${GEMFILE} bundle exec rake unicorn:stop"
}

force_stop()
{
  echo "force stop $NAME"
  su - vagrant -c "cd ${ROOT_DIR} && BUNDLE_GEMFILE=${GEMFILE} bundle exec rake unicorn:stop_f"
}

restart()
{
  echo "restart $NAME"
  su - vagrant -c "cd ${ROOT_DIR} && BUNDLE_GEMFILE=${GEMFILE} bundle exec rake unicorn:restart"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  force-stop)
    force_stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|force-stop|restart]"
    ;;
esac
